version: '3.7'

networks:
  loki:

services:
  elasticsearch:
    image: elasticsearch:7.17.0
    ports:
      - '9200:9200'
    environment:
      - cluster.name= adirn
      - node.name=es01
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.17.0
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.17.0
    ports:
      - '5000:5000'
    volumes:
      - ./logstash_pipeline/:/logstash_dir
      - ./:/log_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch

  zipkins:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  loki:
    image: grafana/loki:2.2.1
    container_name: loki-service
    volumes:
      - ./loki:/etc/loki/
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    networks:
      - loki


  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail-service
    volumes:
      - ./:/var/log/
      - ./promtail:/etc/promtail/
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki


  grafana:
    image: grafana/grafana:latest
    container_name: grafana-service
    ports:
      - "3000:3000"
    networks:
      - loki

  
